/**
 * @license
 * Copyright 2022-2025 Matter.js Authors
 * SPDX-License-Identifier: Apache-2.0
 */

/*** THIS FILE IS GENERATED, DO NOT EDIT ***/

import { MatterDefinition } from "../MatterDefinition.js";
import {
    SemanticNamespaceElement as SemanticNamespace,
    SemanticTagElement as SemanticTag
} from "../../elements/index.js";

export const AreaNamespaceNs = SemanticNamespace(
    { name: "AreaNamespace", id: 0x10 },
    SemanticTag({ name: "Aisle", id: 0x0 }),
    SemanticTag({ name: "Attic", id: 0x1 }),
    SemanticTag({ name: "BackDoor", id: 0x2 }),
    SemanticTag({ name: "BackYard", id: 0x3 }),
    SemanticTag({ name: "Balcony", id: 0x4 }),
    SemanticTag({ name: "Ballroom", id: 0x5 }),
    SemanticTag({ name: "Bathroom", id: 0x6 }),
    SemanticTag({ name: "Bedroom", id: 0x7 }),
    SemanticTag({ name: "Border", id: 0x8 }),
    SemanticTag({ name: "Boxroom", id: 0x9 }),
    SemanticTag({ name: "BreakfastRoom", id: 0xa }),
    SemanticTag({ name: "Carport", id: 0xb }),
    SemanticTag({ name: "Cellar", id: 0xc }),
    SemanticTag({ name: "Cloakroom", id: 0xd }),
    SemanticTag({ name: "Closet", id: 0xe }),
    SemanticTag({ name: "Conservatory", id: 0xf }),
    SemanticTag({ name: "Corridor", id: 0x10 }),
    SemanticTag({ name: "CraftRoom", id: 0x11 }),
    SemanticTag({ name: "Cupboard", id: 0x12 }),
    SemanticTag({ name: "Deck", id: 0x13 }),
    SemanticTag({ name: "Den", id: 0x14 }),
    SemanticTag({ name: "Dining", id: 0x15 }),
    SemanticTag({ name: "DrawingRoom", id: 0x16 }),
    SemanticTag({ name: "DressingRoom", id: 0x17 }),
    SemanticTag({ name: "Driveway", id: 0x18 }),
    SemanticTag({ name: "Elevator", id: 0x19 }),
    SemanticTag({ name: "Ensuite", id: 0x1a }),
    SemanticTag({ name: "Entrance", id: 0x1b }),
    SemanticTag({ name: "Entryway", id: 0x1c }),
    SemanticTag({ name: "FamilyRoom", id: 0x1d }),
    SemanticTag({ name: "Foyer", id: 0x1e }),
    SemanticTag({ name: "FrontDoor", id: 0x1f }),
    SemanticTag({ name: "FrontYard", id: 0x20 }),
    SemanticTag({ name: "GameRoom", id: 0x21 }),
    SemanticTag({ name: "Garage", id: 0x22 }),
    SemanticTag({ name: "GarageDoor", id: 0x23 }),
    SemanticTag({ name: "Garden", id: 0x24 }),
    SemanticTag({ name: "GardenDoor", id: 0x25 }),
    SemanticTag({ name: "GuestBathroom", id: 0x26 }),
    SemanticTag({ name: "GuestBedroom", id: 0x27 }),
    SemanticTag({ name: "Reserved1", id: 0x28 }),
    SemanticTag({ name: "GuestRoom", id: 0x29 }),
    SemanticTag({ name: "Gym", id: 0x2a }),
    SemanticTag({ name: "Hallway", id: 0x2b }),
    SemanticTag({ name: "HearthRoom", id: 0x2c }),
    SemanticTag({ name: "KidsRoom", id: 0x2d }),
    SemanticTag({ name: "KidsBedroom", id: 0x2e }),
    SemanticTag({ name: "Kitchen", id: 0x2f }),
    SemanticTag({ name: "Reserved2", id: 0x30 }),
    SemanticTag({ name: "LaundryRoom", id: 0x31 }),
    SemanticTag({ name: "Lawn", id: 0x32 }),
    SemanticTag({ name: "Library", id: 0x33 }),
    SemanticTag({ name: "LivingRoom", id: 0x34 }),
    SemanticTag({ name: "Lounge", id: 0x35 }),
    SemanticTag({ name: "MediaTvRoom", id: 0x36 }),
    SemanticTag({ name: "MudRoom", id: 0x37 }),
    SemanticTag({ name: "MusicRoom", id: 0x38 }),
    SemanticTag({ name: "Nursery", id: 0x39 }),
    SemanticTag({ name: "Office", id: 0x3a }),
    SemanticTag({ name: "OutdoorKitchen", id: 0x3b }),
    SemanticTag({ name: "Outside", id: 0x3c }),
    SemanticTag({ name: "Pantry", id: 0x3d }),
    SemanticTag({ name: "ParkingLot", id: 0x3e }),
    SemanticTag({ name: "Parlor", id: 0x3f }),
    SemanticTag({ name: "Patio", id: 0x40 }),
    SemanticTag({ name: "PlayRoom", id: 0x41 }),
    SemanticTag({ name: "PoolRoom", id: 0x42 }),
    SemanticTag({ name: "Porch", id: 0x43 }),
    SemanticTag({ name: "PrimaryBathroom", id: 0x44 }),
    SemanticTag({ name: "PrimaryBedroom", id: 0x45 }),
    SemanticTag({ name: "Ramp", id: 0x46 }),
    SemanticTag({ name: "ReceptionRoom", id: 0x47 }),
    SemanticTag({ name: "RecreationRoom", id: 0x48 }),
    SemanticTag({ name: "Reserved3", id: 0x49 }),
    SemanticTag({ name: "Roof", id: 0x4a }),
    SemanticTag({ name: "Sauna", id: 0x4b }),
    SemanticTag({ name: "Scullery", id: 0x4c }),
    SemanticTag({ name: "SewingRoom", id: 0x4d }),
    SemanticTag({ name: "Shed", id: 0x4e }),
    SemanticTag({ name: "SideDoor", id: 0x4f }),
    SemanticTag({ name: "SideYard", id: 0x50 }),
    SemanticTag({ name: "SittingRoom", id: 0x51 }),
    SemanticTag({ name: "Snug", id: 0x52 }),
    SemanticTag({ name: "Spa", id: 0x53 }),
    SemanticTag({ name: "Staircase", id: 0x54 }),
    SemanticTag({ name: "SteamRoom", id: 0x55 }),
    SemanticTag({ name: "StorageRoom", id: 0x56 }),
    SemanticTag({ name: "Studio", id: 0x57 }),
    SemanticTag({ name: "Study", id: 0x58 }),
    SemanticTag({ name: "SunRoom", id: 0x59 }),
    SemanticTag({ name: "SwimmingPool", id: 0x5a }),
    SemanticTag({ name: "Terrace", id: 0x5b }),
    SemanticTag({ name: "UtilityRoom", id: 0x5c }),
    SemanticTag({ name: "Ward", id: 0x5d }),
    SemanticTag({ name: "Workshop", id: 0x5e }),
    SemanticTag({ name: "Toilet", id: 0x5f })
);

MatterDefinition.children.push(AreaNamespaceNs);
