#!/usr/bin/env node
/**
 * @license
 * Copyright 2022-2026 Matter.js Authors
 * SPDX-License-Identifier: Apache-2.0
 */

// Validates that the published .d.ts artifacts of @matter/* packages compile cleanly under strict
// TypeScript without skipLibCheck and without dev-only resolution conditions.  Catches issues that
// matter.js's internal build hides via skipLibCheck=true and customConditions=["dev-types"], but
// which downstream consumers using strict TS will hit.
//
// Run via: `npm run validate-dts`

import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const REPO_ROOT = resolve(dirname(__filename), "..", "..");

// Core packages whose .d.ts is generated by matter.js codegen.  Platform/runtime adapter packages
// (nodejs-ble, nodejs-ws, mqtt, react-native, cli-tool) are excluded because their .d.ts surfaces
// reflect transitive dependency type quality (react-native, memlab, etc.) which is outside our
// control.
const PACKAGES = [
    "@matter/general",
    "@matter/model",
    "@matter/types",
    "@matter/protocol",
    "@matter/node",
    "@matter/main",
    "@matter/testing",
    "@matter/nodejs",
    "@project-chip/matter.js",
];

// An error is attributed to matter.js if its file path is inside one of these prefixes (matched
// against the path printed by tsc, normalized to forward slashes for cross-platform consistency).
// Transitive deps and TypeScript's bundled lib are ignored because they're not produced by our
// codegen.  We also flag errors whose body references a matter package (e.g. TS2307 from a missing
// `import "@matter/..."` in the harness) so a broken harness can't silently pass.
const MATTER_PATH_FRAGMENTS = ["/@matter/", "/@project-chip/matter.js/"];
const MATTER_MODULE_FRAGMENTS = ["'@matter/", '"@matter/', "'@project-chip/matter.js", '"@project-chip/matter.js'];

// Errors that always indicate the harness itself is broken.  Treat as hard failures.
//   TS2307 — Cannot find module 'X' (failed import)
//   TS2792 — Cannot find module (with did-you-mean)
//   TS2882 — Cannot find module or type declarations for side-effect import
//   TS6053 — File not found
const FATAL_HARNESS_ERROR_CODES = ["TS2307", "TS2792", "TS2882", "TS6053"];

// Errors tolerated under the CJS pass only.  The CJS bundle of @matter/general imports `@noble/
// curves` subpaths via `import`/type-import — but `@noble/curves` v2+ is ESM-only.  Under node16
// CJS resolution this is illegal.  ESM consumers (the primary distribution) are unaffected.
// Tracked separately; these codes are NOT tolerated in the ESM pass or outside dist/cjs.
//   TS1479 — CommonJS file imports an ESM module
//   TS1542 — Type import of ESM module from CJS missing 'resolution-mode' attribute
const CJS_ALLOWED_ERROR_CODES = ["TS1479", "TS1542"];
const CJS_ALLOWED_PATH_FRAGMENT = "/dist/cjs/";

function tscPath() {
    return resolve(REPO_ROOT, "node_modules", "typescript", "bin", "tsc");
}

function normalizePath(line) {
    return line.replaceAll(sep, "/").replaceAll("\\\\", "/");
}

function isMatterError(line) {
    const normalized = normalizePath(line);
    return (
        MATTER_PATH_FRAGMENTS.some(frag => normalized.includes(frag)) ||
        MATTER_MODULE_FRAGMENTS.some(frag => line.includes(frag))
    );
}

function isFatalHarnessError(line) {
    return FATAL_HARNESS_ERROR_CODES.some(code => line.includes(`error ${code}:`));
}

function isCjsAllowedError(line) {
    const normalized = normalizePath(line);
    if (!normalized.includes(CJS_ALLOWED_PATH_FRAGMENT)) return false;
    return CJS_ALLOWED_ERROR_CODES.some(code => line.includes(`error ${code}:`));
}

/**
 * Run a single tsc pass against the synthetic consumer and classify diagnostics.  The caller
 * supplies the compilerOptions for the pass; everything else (the import list, harness self-check,
 * matter-vs-noise filtering) is shared.
 *
 * @param {string} label - "ESM" or "CJS", used only for log output
 * @param {object} compilerOptions - tsconfig compilerOptions for this pass
 * @param {(line: string) => boolean} extraIgnore - additional predicate for ignoring lines
 * @returns {{ matterErrors: string[], harnessErrors: string[], ignoredCount: number }}
 */
function runPass(label, compilerOptions, extraIgnore = () => false) {
    const tmp = mkdtempSync(join(tmpdir(), `matter-dts-${label.toLowerCase()}-`));
    try {
        const importStatements = PACKAGES.map(p => `import ${JSON.stringify(p)};`).join("\n");
        writeFileSync(join(tmp, "repro.ts"), `${importStatements}\n`);

        writeFileSync(join(tmp, "tsconfig.json"), JSON.stringify({ compilerOptions, include: ["repro.ts"] }, null, 4));

        // Symlink node_modules from the repo so imports resolve against built dist.  Use Node's fs
        // API (not `ln`) for cross-platform support; "junction" works on Windows for directories.
        try {
            symlinkSync(join(REPO_ROOT, "node_modules"), join(tmp, "node_modules"), "junction");
        } catch (err) {
            console.error(`✗ [${label}] Failed to create node_modules symlink: ${err.message}`);
            process.exit(2);
        }

        const tsc = tscPath();
        if (!existsSync(tsc)) {
            return { spawnError: `tsc binary not found at ${tsc}` };
        }

        const result = spawnSync(process.execPath, [tsc, "-p", "."], {
            cwd: tmp,
            encoding: "utf8",
        });

        const output = `${result.stdout || ""}${result.stderr || ""}`;
        const errorLines = output.split("\n").filter(l => l.includes("error TS"));

        // Distinguish a real tsc invocation from a spawn failure.  tsc returns 0 on a clean
        // type-check (no output) or 1/2 with `error TS` lines when it reports diagnostics.  Any
        // other state — process killed by signal (status=null), spawn ENOENT (result.error), or
        // non-zero exit with no diagnostics produced — means tsc didn't actually run a check.
        if (result.error || result.status === null || (result.status !== 0 && errorLines.length === 0)) {
            const detail =
                result.error?.message ??
                (result.status === null
                    ? `terminated by signal ${result.signal}`
                    : `exit ${result.status} with no diagnostics; stderr:\n${result.stderr}`);
            return { spawnError: detail };
        }

        // Bucket diagnostics into disjoint sets so counts add up:
        //   harness errors — repro.ts lines that imply the validator never ran the actual check
        //   matter errors  — code-owned errors outside repro.ts (after the CJS/ESM allowlist)
        //   ignored        — everything else (transitive deps, lib bundle bugs, etc.)
        const harnessErrors = errorLines.filter(
            l => l.includes("repro.ts") && (isFatalHarnessError(l) || isMatterError(l)),
        );
        const harnessSet = new Set(harnessErrors);
        const matterErrors = errorLines.filter(l => !harnessSet.has(l) && isMatterError(l) && !extraIgnore(l));
        const ignoredCount = errorLines.length - matterErrors.length - harnessErrors.length;

        return { matterErrors, harnessErrors, ignoredCount };
    } finally {
        rmSync(tmp, { recursive: true, force: true });
    }
}

function reportPass(label, result) {
    if (result.spawnError) {
        console.error(`✗ [${label}] tsc invocation failed: ${result.spawnError}`);
        return 2;
    }
    if (result.harnessErrors.length > 0) {
        console.error(`✗ [${label}] Harness self-check failed — validator did not actually validate the packages:\n`);
        for (const err of result.harnessErrors) {
            console.error(err);
        }
        return 2;
    }
    if (result.matterErrors.length === 0) {
        console.log(
            `✓ [${label}] All ${PACKAGES.length} packages produce clean .d.ts ` +
                `(${result.ignoredCount} non-matter errors ignored)`,
        );
        return 0;
    }
    console.error(`✗ [${label}] ${result.matterErrors.length} matter.js .d.ts error(s):\n`);
    for (const err of result.matterErrors) {
        console.error(err);
    }
    console.error(`\n${result.ignoredCount} non-matter errors ignored.`);
    return 1;
}

function main() {
    // Two passes mirror the two artifacts each package ships:
    //   ESM (primary):  module=esnext + moduleResolution=bundler — what modern bundler/Node ESM
    //                   consumers see.  Strict; no allowlist.
    //   CJS (fallback): module=node16 + moduleResolution=node16 — what pure-CJS Node consumers see.
    //                   Tolerates documented TS1479/TS1542 in matter's dist/cjs (caused by
    //                   ESM-only deps such as @noble/curves); strict otherwise.
    const esmResult = runPass("ESM", {
        target: "esnext",
        module: "esnext",
        moduleResolution: "bundler",
        strict: true,
        noEmit: true,
        skipLibCheck: false,
    });
    const esmExit = reportPass("ESM", esmResult);

    const cjsResult = runPass(
        "CJS",
        {
            target: "esnext",
            module: "node16",
            moduleResolution: "node16",
            strict: true,
            noEmit: true,
            skipLibCheck: false,
            esModuleInterop: true,
        },
        isCjsAllowedError,
    );
    const cjsExit = reportPass("CJS", cjsResult);

    process.exit(Math.max(esmExit, cjsExit));
}

main();
